config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'users/index'
  get 'users/show'

  devise_for :users

  root 'static_pages#overview'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'hiev_stats' => 'static_pages#hiev_stats'
  get 'hiev_usage' => 'static_pages#hiev_usage'
  get 'hiestorage_stats' => 'static_pages#hiestorage_stats'
  get 'eucface' => 'static_pages#eucface'
  get 'eucface_camera' => 'static_pages#eucface_camera'

  resources :users

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  before_save { self.email = email.downcase }
  
  after_create :send_admin_mail, :send_welcome_mail
  
  # Set out different user roles available
  def self.roles
    ['user', 'superuser', 'admin']
  end
         
  validates :firstname, presence: true, length: { maximum: 30 }
  validates :surname, presence: true, length: { maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 80 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  
  validates_inclusion_of :role, in: self.roles
  validate :name_has_no_numbers
  
  ## Custom validations
  def name_has_no_numbers
    errors.add(:base, "First Name or Surname can not contain numbers") if
      /\d/.match( self.firstname ) || /\d/.match( self.surname )
  end
  
  # Devise 'approved' settings
  def active_for_authentication? 
    super && approved? 
  end 

  def inactive_message 
    if !approved? 
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end
  
  def send_admin_mail
    UserMailer.new_user_waiting_for_approval(self).deliver_now
  end
  
  def send_welcome_mail
    UserMailer.welcome_email(self).deliver_now
  end
  
  def fullname
    self.firstname << " " << self.surname
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  

  # Update for adding first name and surname to devise user model 
  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protected

  def configure_devise_permitted_parameters
    registration_params = [:firstname, :surname, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
  end  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def overview
  end

  def help
  end

  def about
  end

  def contact
  end

  def hiev_stats
    render :template => "static_pages/hiev/hiev_stats"
  end

  def hiev_usage
    render :template => "static_pages/hiev/hiev_usage"
  end

  def hiestorage_stats
    render :template => "static_pages/hiestorage/hiestorage_stats"
  end

  def eucface
    render :template => "static_pages/eucface/eucface_main"
  end

  def eucface_camera
    render :template => "static_pages/eucface/eucface_camera"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index   
    @users = User.paginate(page: params[:page])
  end
  
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "HIE Current Data"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
  
  # Is the given link the current page?
  def is_active?(link_path)
    current_page?(link_path)
  end
    
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
  <div class="container">
    <hr>
    <!-- Footer -->
    <footer>
      <div class="row">
        <div class="col-lg-12">
          <p>Hawkesbury Institute for the Environment,</p>
          <p>Western Sydney University</p>
        </div>
      </div>
    </footer>
  </div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "HIE Current Data", root_path, class: "navbar-brand"  %>
    </div>
    
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    </div>
    <!-- /.navbar-collapse -->
  </div>
    <!-- /.container -->
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>HIE Current Data</title>
		<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <meta name="description" content="Current Data Views at Hawkesbury Institute for the Environment" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
	</head>

	<body>
    <div class="container">

			    <!-- Header Bar -->
			    <%= render 'layouts/header' %>

			    <!-- Page Heading -->
			    <h1 class="bottomspace padded_sides_10"><%= yield(:pageheading) %></h1>

					<!-- Page Content -->
			    <div class="container">
			      <div class="row">
			        <div class="col-md-3">
			          <div class="list-group">
			          	<% if is_active?(root_path) %>
			              <%= link_to "Overview", root_path, :class=>"list-group-item active" %>
			            <% else %>
			              <%= link_to "Overview", root_path, :class=>"list-group-item" %>
			            <% end %>

			          	<% if is_active?(hiev_stats_path) %>
			              <%= link_to "HIEv Stats", hiev_stats_path, :class=>"list-group-item active" %>
			            <% else %>
			              <%= link_to "HIEv Stats", hiev_stats_path, :class=>"list-group-item" %>
			            <% end %>

									<% if is_active?(hiev_usage_path) %>
			              <%= link_to "HIEv Usage", hiev_usage_path, :class=>"list-group-item active" %>
			            <% else %>
			              <%= link_to "HIEv Usage", hiev_usage_path, :class=>"list-group-item" %>
			            <% end %>

									<% if is_active?(hiestorage_stats_path) %>
			              <%= link_to "HIE-Storage Stats", hiestorage_stats_path, :class=>"list-group-item active" %>
			            <% else %>
			              <%= link_to "HIE-Storage Stats", hiestorage_stats_path, :class=>"list-group-item" %>
			            <% end %>

			            <% if is_active?(eucface_path) %>
			              <%= link_to "EucFACE", eucface_path, :class=>"list-group-item active" %>
			            <% else %>
			              <%= link_to "EucFACE", eucface_path, :class=>"list-group-item" %>
			            <% end %>

			          </div>
			        </div>
			    	  <%= yield %>
			      </div>
			    </div>

			    <!-- Footer -->
			    <%= render 'layouts/footer' %>

    </div>
	</body>
</html>

app/views/static_pages/eucface/eucface_camera.html.erb
<% provide(:pageheading, 'CUP supersite snapshot ') %>

<div class="col-md-9">
 <div class="row">
    <div class="col-md-8 col-md-offset-1">
      <ul>
			  <li>Photo taken daily at 9:00am (including DST if active) * Photo upload to this site will occur in the following hours (check the image for actual date of photo) </li>
			  <li>View from EucFACE Ring 1</li>
			  <li>Camera settings (API): pan=-143, tilt=0.6, zoom=460</li>
			</ul>  
    </div>
  </div>
  <div class="row topspace20">
    <div class="col-md-8 col-md-offset-2">
		  <div class="thumbnail">	
        <a href='photos/face/eucface_camera.jpg'><img src="photos/face/eucface_camera.jpg"></a>
      </div>
    </div>
  </div>
</div>
        

app/views/static_pages/eucface/eucface_main.html.erb
<% provide(:pageheading, 'EucFACE') %>

<div class="col-md-9">

  <div class="thumbnail">
    <div class="caption-full">
      <h4 class="pull-right">Photo</h4>
      <h4 class="pink_writing">Face Surveillance Camera</h4>
      <p>Daily snapshot from the canopy at EucFACE and the adjacent Supersite in the background</p>
    </div>
    <div class="padded_sides_10 pink_writing">
      <p class="pull-right"><%= link_to "View", eucface_camera_path %></p>
      <p>Available in HIEv</p>
    </div>
  </div>  

</div>

app/views/static_pages/hiestorage/hiestorage_stats.html.erb
<% provide(:pageheading, 'HIE-Storage Stats') %>

<div class="col-md-9">
	<p>
    The following table shows the current data volumes/numbers and daily transfer activity for each folder within the HIE-Storage 'Working data' folder (Projects, Sensors, etc).
  </p>
  <br/>
  <div id="todaysdate">
    Date =
	</div>
  <br/>
	<table id="hiestorage_stats" class="table table-striped table-hover table-bordered">
		<thead>
			<th>Facility</th>
			<th>Data type</th>
			<th>Name</th>
			<th>Number of files</th>
			<th>Number of files transferred (last 24 hrs)</th>
			<th>Data volume (MB)</th>
			<th>Data volume transferred (MB) (last 24 hrs) </th>
		</thead>
		<tbody>
		</tbody>
	</table>

</div>

app/views/static_pages/hiev/hiev_stats.html.erb
<% provide(:pageheading, 'HIEv Data listings') %>

<div class="col-md-9">

	<p>The following is a breakdown of data listings currently in the HIEv data capture application. Different statistics are
		listed, from overall numbers of files in HIEv right down to the number of files per file type per facility for example. Note that
		the statistics are generated around midnight each night (see timestamp below) and so will not account for any files that have been uploaded after that
		point.</p>
  <h2 class="pink_writing topspace20">Summary</h2>
	<div id="summary">
	</div>

  <h2 class="pink_writing topspace50">File Type Summary</h2>
  <table class="table table-striped table-hover table-bordered">
  	<thead>
  	  <th>File Type</th>
  	  <th>Total files</th>
  	  <th>Uploaded in last day</th>
  	</thead>
	  <tbody id="file_type_summaries">
	  </tbody>
	</table>


  <h2 class="pink_writing topspace50">Facility Summary</h2>
  <table class="table table-striped table-hover table-bordered">
  	<thead>
  	  <th>Facility Name</th>
  	  <th>Total files</th>
  	  <th>Uploaded in last day</th>
  	</thead>
	  <tbody id="facility_summaries">
	  </tbody>
	</table>


  <h2 class="pink_writing topspace50">Facility Detail</h2>
	<div id="facility_detail">
	</div>



</div>

app/views/static_pages/hiev/hiev_usage.html.erb
<% provide(:pageheading, 'HIEv Usage') %>

<div class="col-md-9">

	<p>
    The following table lists the number of requests (search, download file, etc)
    made to the HIEV application each day. This includes requests made via both the
    HIEV webpage and the HIEV API. Currently, the stats list total requests
    made, as well as requests originating from the
    <a href="https://bitbucket.org/remkoduursma/hiev">HIEv R</a> package. It should
    be noted that the tallys recorded include the individual requests,
    of which there may be several (e.g. looping over search API calls), made within
    individual hiev-interfacing scripts.
  </p>

  <br/>
  
	<table id="results" class="table table-striped table-hover table-bordered">
		<thead>
			<th>Date</th>
			<th>Total HIEv requests</th>
			<th>Total HIEvR requests</th>
			<th>Total HIEvR Search requests</th>
		</thead>
		<tbody>
		</tbody>
	</table>

</div>

app/views/static_pages/overview.html.erb
<% provide(:pageheading, 'Overview') %>

<div class="col-md-9">
   <h2 class="pink_writing">Overview</h2>
   <p>The HIE Current Data pages show the current status of different data streams and data statistics within HIE. If you would like to 
   	have a particular set of data added to these pages please email g.devine@westernsydney.edu.au to discuss.</p>   
</div>
        

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>